-- +migrate Up
CREATE TABLE IF NOT EXISTS tbl_roles (
   role_id SERIAL PRIMARY KEY,
   nm_role VARCHAR(50) UNIQUE NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS tbl_roles;
